DATA_SKILLS = [
    'APACHE', 'C++', 'Financial Statement', 'MongoDB', 'R', 'Python', 'Java', 'Microsoft Excel', 'Tableau', 'Statistics',
    'Natural Language Processing (NLP)', 'Unsupervised Machine Learning', 'Structured Query Language (SQL)', 'Computer Vision',
    'Supervised Machine Learning', 'Matlab', 'Extract Transform Load (ETL)', 'Deep Learning', 'Dashboard', 'NOSQL',
    'Apache Spark', 'Artificial Intelligence (AI)', 'Time Series Analysis', 'Microsoft Power BI', 'Regression',
    'Reinforcement Learning', 'Graph Theory', 'Database Management System (DBMS)', 'Apache Hadoop', 'Cloud Technology',
    'Data Cleansing', 'Data Preparation', 'Github', 'JavaScript', 'Presentation', 'AB Testing', 'Visualization'
]

MAP_TO_DATA_SKILLS = {
    'Machine Learning': 'AI',
    'Amazon Web Service (AWS)': 'Cloud Technologies',
    'Google Cloud Platform (GCP)': 'Cloud Technologies',
    'Microsoft Azure': 'Cloud Technologies',
    'IBM Cloud': 'Cloud Technologies',
    'Alibaba Cloud': 'Cloud Technologies',
    'Oracle Cloud': 'Cloud Technologies',
    'SAP Cloud Platform': 'Cloud Technologies',
    'Rackspace Cloud': 'Cloud Technologies',
    'VMWare': 'Cloud Technologies',
    'DigitalOcean': 'Cloud Technologies',
    'Kamatera': 'Cloud Technologies',
    'Serverspace': 'Cloud Technologies',
    'Linode': 'Cloud Technologies',
    'OpenNebula': 'Cloud Technologies',
    'Linear Regression': 'Supervised Machine Learning',
    'Classification': 'Supervised Machine Learning',
    'Naïve Bayes': 'Supervised Machine Learning',
    'Artificial Neural Network (ANN)': 'Supervised Machine Learning',
    'Convolutional Neural Network (CNN)': 'Deep Learning',
    'Decision Tree': 'Supervised Machine Learning',
    'Gated Recurrent Unit (GRU)': 'Deep Learning',
    'Generative Adversarial Network (GAN)': 'Deep Learning',
    'k-means Clustering': 'Unsupervised Machine Learning',
    'k-Nearest Neighbour (kNN)': 'Supervised Machine Learning',
    'Linear Discriminant Analysis (LDA)': 'Unsupervised Machine Learning',
    'Logistic Regression': 'Supervised Machine Learning',
    'Long Short-Term Memory (LSTM)': 'Deep Learning',
    'Principal Component Analysis (PCA)': 'Unsupervised Machine Learning',
    'Random Forest': 'Supervised Machine Learning',
    'Clustering': 'Unsupervised Machine Learning'
}

SKILL_DICT = {
    'Financial Statement': 'Financial Statements',
    'MongoDB': 'Mongo DB',
    'R': 'R programming',
    'Python': 'Python Programming',
    'Microsoft Excel': 'Excel',
    'Natural Language Processing (NLP)': 'NLP',
    'Structured Query Language (SQL)': 'SQL', 
    'Extract Transform Load (ETL)': 'ETL',
    'Dashboard': 'Dashboards',
    'Apache Spark': 'SPARK',
    'Artificial Intelligence (AI)': 'AI',
    'Microsoft Power BI': 'Power BI',
    'Regression': 'Regressions',
    'Reinforcement Learning': 'Reinforcement',
    'Database Management System': 'DBMS',
    'Apache Hadoop': 'Hadoop',
    'Cloud Technology': 'Cloud Technologies',
    'Data Cleansing': 'Data Cleansing / Preparation',
    'Data Preparation': 'Data Cleansing / Preparation',
    'Presentation': 'Presentation Skill',
    'Visualization': 'Visualizations',
}