apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ds-training-content-scraper
  namespace: development
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - python
                - main.py
              envFrom:
                - secretRef:
                    name: ds-training-content-scraper
              image: registry.gitlab.com/cads-platform-ds-projects/training-content-scraper:latest
              imagePullPolicy: IfNotPresent
              name: training-content-scraper-crontab
          imagePullSecrets:
            - name: regcred-ds-projs
          restartPolicy: Never
  schedule: 0 3 * * *
  successfulJobsHistoryLimit: 3
